name: Tecton Feature Repo Test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ "brian/2022-02-04/ci" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Environment
      run: env | grep ENVIRONMENT || true

    - name: Environment with override
      run: env | grep ENVIRONMENT
      env:
        ENVIRONMENT: EVVVV
        TECTON_ENVIRONMENT: TECTON_EVVVV
