name: Tecton Feature Repo CI/CD

on:
  push:
    branches: [ main ]

jobs:
  tecton-apply:
    runs-on: ubuntu-latest
    env:
      TECTON_API_KEY: ${{ secrets.TECTON_API_KEY }}
      API_SERVICE: https://app.tecton.ai/api
      TECTON_WORKSPACE: prod-brian
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.7.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.7.10

    - name: Install the Tecton CLI
      run: pip install pypandoc && pip install 'tecton[pyspark]'

    - name: Run tecton apply
      run: tecton apply --no-safety-check
      working-directory: fraud
